web:
   image: web
   environment:
     - ALLOW_OVERRIDE=true
   ports:
     - "81:80"
   links:
     - db
   volumes:
     - ./app:/var/www/html/

db:
  image: mariadb:10.8.2
  restart: always
  volumes:
    - ./mysql:/var/lib/mysql
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: lK9pF81rtVq1
    MYSQL_PASSWORD: o80dGpAMjKb2
    MYSQL_DATABASE: database
  ports:
    - "8889:3306"

phpmyadmin:
  image: phpmyadmin/phpmyadmin:latest
  links:
    - db
  ports:
    - 8890:80
  environment:
    MYSQL_USER: lK9pF81rtVq1
    MYSQL_PASSWORD: o80dGpAMjKb2
    MYSQL_DATABASE: database
